[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/member/*"
  to = "/member.html"
  status = 200

[[redirects]]
  from = "/member-status"
  to = "/.netlify/functions/member-card"
  status = 200
  force = true
